spring:
  application:
    name: kafkamplify
  kafka:
    global.embedded.enabled: true
    listener:
      ack-mode: batch
      concurrency: 2
    consumer:
      max-poll-records: 800

#logging:
#  level:
#    root: DEBUG